version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3  
    container_name: keycloak
    ports:
      - "8180:8080"  
    environment:
      KEYCLOAK_ADMIN: admin                  
      KEYCLOAK_ADMIN_PASSWORD: admin         
      KC_DB: postgres                        
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak  
      KC_DB_USERNAME: keycloak               
      KC_DB_PASSWORD: password               
      KC_HOSTNAME: localhost                 
    depends_on:
      - db                                   
    command: ["start-dev"]
    networks:
      - keycloak-network

  db:
    image: postgres:13                       
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak                  
      POSTGRES_USER: keycloak                
      POSTGRES_PASSWORD: password            
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data  
    networks:
      - keycloak-network

volumes:
  keycloak-db-data:                          

networks:
  keycloak-network:
    driver: bridge