INSERT IGNORE INTO `Category` (`sequId`, `title`) VALUES
(1, 'Home'),
(2, 'Gardening & Outdoor'),
(3, 'Technology'),
(4, 'Fashion & Style');

INSERT IGNORE INTO `product` (`sequId`, `deleteAt`, `description`, `imgResources`, `imgResources2`, `imgResources3`, `price`, `stock`, `title`, `category_sequId`) VALUES
(1, '2025-03-23 18:48:56.000000', 'Prova', 'https://i.imgur.com/66Ctq4o.png', 'https://i.imgur.com/66Ctq4o.png', 'https://i.imgur.com/66Ctq4o.png', 12.09, 5, 'Prova', 1),
(2, '2025-03-23 18:48:51.000000', 'Descrizione del prodotto 1', 'https://i.imgur.com/66Ctq4o.png', NULL, NULL, 10.00, 100, 'Prodotto 1', 1),
(3, '2025-03-23 18:48:53.000000', 'Descrizione del prodotto 1', 'https://i.imgur.com/66Ctq4o.png', NULL, NULL, 10.00, 100, 'Prodotto 2', 1),
(4, NULL, 'An automatic drip irrigation system for gardens and potted plants. Includes a timer, 20-meter tubing, and 30 drip nozzles. <br> Perfect for maintaining consistent watering schedules and conserving water. \n<br> Easy to set up and customizable for any garden size.', 'https://i.imgur.com/t5HnsXR.png', 'https://i.imgur.com/p3Wmoq8.png', NULL, 49.00, 67, 'ProGrow Watering System', 2),
(5, NULL, 'A lightweight and portable folding table designed for outdoor use. Features a weather-resistant surface and adjustable legs for uneven terrain. <br> Perfect for picnics, camping, or gardening activities. Easy to store and transport.', 'https://imgur.com/qXCPdC1.png', 'https://imgur.com/J3yEYMh.png', NULL, 59.00, 94, 'Compact Folding Garden Table', 2),
(6, NULL, 'A set of 6 solar-powered garden lights with automatic dusk-to-dawn operation. Features a waterproof design and durable stainless steel construction. <br> Perfect for illuminating pathways, gardens, or outdoor spaces. Easy to install and energy-efficient.', 'https://imgur.com/5UEetge.png', NULL, NULL, 39.00, 98, 'SolarGlow Garden Lights', 2),
(7, NULL, 'A lightweight and powerful laptop designed for productivity on the go. Features a 14-inch Full HD display, 8GB RAM, 256GB SSD, and an Intel Core i5 processor. <br> Perfect for students, professionals, and everyday use. Includes a backlit keyboard and up to 10 hours of battery life.', 'https://imgur.com/pk2BSbH.png', 'https://imgur.com/IExT0wf.png', NULL, 799.00, 99, 'UltraSlim 14\" Laptop', 3),
(8, NULL, 'A sleek and powerful ultrabook with a 14-inch 4K display, Intel Core i7 processor, 16GB RAM, and 512GB SSD. <br> Features a backlit keyboard, fingerprint reader, and up to 12 hours of battery life. Perfect for professionals and creatives.', 'https://imgur.com/8s5iPnn.png', 'https://imgur.com/T5NM2EZ.png', NULL, 1299.00, 100, 'QuantumBook 14\" Ultrabook', 3),
(9, NULL, 'A compact 4K action camera with waterproof housing, image stabilization, and Wi-Fi connectivity. <br> Includes a variety of mounts for versatile recording options. Perfect for capturing adventures and sports.', 'https://imgur.com/6O1pb7c.png', 'https://imgur.com/3uESPMO.png', NULL, 199.00, 96, 'PixelView 4K Action Camera', 3),
(10, NULL, 'A high-performance desktop PC with an AMD Ryzen 7 processor, 32GB RAM, 1TB SSD, and NVIDIA RTX 3060 graphics. <br> Ideal for gaming, video editing, and multitasking. Includes a 27-inch 144Hz monitor.', 'https://imgur.com/Tp3esac.png', 'https://imgur.com/ueWPALi.png', 'https://imgur.com/wGA529G.png', 650.23, 94, 'SmartCore Desktop PC', 3),
(11, NULL, 'A 27-inch QHD gaming monitor with 165Hz refresh rate and 1ms response time. <br> Features AMD FreeSync, HDR support, and adjustable stand. Perfect for competitive gaming and immersive experiences.', 'https://imgur.com/gSq1SXZ.png', 'https://imgur.com/w9hQqUO.png', 'https://imgur.com/KIfmLdd.png', 349.00, 97, 'ProStream Gaming Monitor', 3),
(12, NULL, 'A 10-inch tablet with a Full HD display, octa-core processor, 128GB storage, and expandable memory. <br> Perfect for streaming, browsing, and light productivity. Includes a detachable keyboard.', 'https://i.imgur.com/0b5maw9.png', 'https://i.imgur.com/ZE37UF5.png', 'https://i.imgur.com/mx5PQQW.png', 299.00, 97, 'UltraTab 10\" Tablet', 3),
(13, NULL, 'A 55-inch 4K UHD Smart TV with HDR10+ and Dolby Vision for stunning picture quality. <br> Features built-in streaming apps, voice control, and a 120Hz refresh rate. Perfect for movies, gaming, and everyday use.', 'https://imgur.com/zMeYb1G.png', 'https://imgur.com/xHDfU4S.png', 'https://imgur.com/zJTek5h.png', 599.00, 96, 'CrystalView 55\" 4K Smart TV', 3),
(14, NULL, 'A 43-inch Full HD TV with a slim design and energy-efficient LED display. <br> Features HDMI and USB ports, built-in speakers, and easy setup. Perfect for smaller spaces or as a secondary TV..', 'https://imgur.com/wn49GT7.png', 'https://imgur.com/Djfm5T5.png', 'https://imgur.com/FSX6LlP.png', 299.00, 96, 'UltraThin 43\" Full HD TV', 3),
(15, NULL, 'A 27-inch 4K UHD monitor with HDR10 support and a 60Hz refresh rate. <br> Features adjustable stand, HDMI/DisplayPort connectivity, and flicker-free technology. Perfect for designers, editors, and professionals.', 'https://imgur.com/DyJn52K.png', 'https://imgur.com/UK6yLDP.png', 'https://imgur.com/ffxjxKW.png', 249.00, 97, 'ProDisplay 27\" 4K Monitor', 3),
(16, NULL, 'A 32-inch curved gaming monitor with 144Hz refresh rate and 1ms response time. <br> Features AMD FreeSync, ultra-wide QHD resolution, and customizable RGB lighting. Perfect for immersive gaming experiences.', 'https://imgur.com/PRHVNGn.png', 'https://imgur.com/e7NskJR.png', 'https://imgur.com/KB73y8x.png', 349.00, 99, 'GameView 32\" Curved Gaming Monitor', 3),
(17, NULL, 'A sleek and functional backpack designed for urban travelers. Features multiple compartments, a padded laptop sleeve, and water-resistant material. <br> Includes a USB charging port and anti-theft zippers. Perfect for daily commutes or weekend getaways.', 'https://imgur.com/Qip49ik.png', NULL, NULL, 89.00, 99, 'UrbanVoyager Backpack', 4),
(18, NULL, 'Timeless aviator-style sunglasses with UV400 protection and polarized lenses. <br> Features a lightweight metal frame and comes with a protective case. Perfect for sunny days or outdoor adventures.', 'https://imgur.com/6wWn53c.png', NULL, NULL, 59.00, 99, 'ClassicAviator Sunglasses', 4),
(19, NULL, 'Lightweight and breathable running shoes with cushioned soles and a modern design. <br> Available in multiple colors and sizes. Perfect for workouts, running, or casual wear.', 'https://imgur.com/laYlRoD.png', 'https://imgur.com/pOOg4r5.png', NULL, 89.00, 100, 'SportLuxe Running Shoes', 4),
(20, NULL, 'A sleek and elegant leather watch with a minimalist dial and stainless steel case. <br> Available in black, brown, and navy straps. Perfect for formal or casual occasions.', 'https://imgur.com/9pXKy6O.png', NULL, NULL, 89.00, 99, 'Minimalist Leather Watch', 4)
;